const ADD_JOB = "ADD_JOB"
const FILTER_JOB = "FILTER_JOB"
const HANDLE_CHECKED = "HANDLE_CHECKED"
const EDIT_JOB = "EDIT_JOB"
const DELETE_JOB = "DELETE_JOB"
export { ADD_JOB, FILTER_JOB, HANDLE_CHECKED, EDIT_JOB, DELETE_JOB }